# Generated by Django 5.1.1 on 2024-10-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archive",
            name="ans1",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="archive",
            name="ans2",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="archive",
            name="ans3",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="archive",
            name="ans4",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="archive",
            name="ans5",
            field=models.TextField(),
        ),
    ]
